version: "2"

services:

    web:
        container_name: partypocker_fpm
        build: .
        volumes:
            - ./:/var/www/vhosts/site/
        working_dir: /var/www/vhosts/site
        links:
            - mysql:mysql
        command: "/usr/sbin/php-fpm7.1 -F -O"
        user: "www-data"

    nginx:
        container_name: partypocker_nginx
        image: nginx
        expose:
            - "80"
        ports:
            - "80:80"
        volumes:
            - /var/www/vhosts/site
            - ./etc/nginx:/etc/nginx
        volumes_from:
            - web
        links:
            - web:web


    mysql:
        container_name: partypocker_mysql
        image: mysql:5.7
        volumes:
            - ./etc/mysql:/etc/mysql/conf.d
            - ./storage/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
